[project]
name = "r2t2"
description = "A simple, fast, top-down Ray Tracing Terrain Renderer (R2T2)"
version = "0.5.2"

[build-system]
requires = ["taichi", "numpy", "noise", "scipy", "tqdm", "opencv-python"]
