[project]
name = "r2t2"
description = "A simple, fast, top-down Ray Tracing Terrain Renderer (R2T2)"
version = "0.6.0"

[build-system]
build-backend = "setuptools.build_meta"
requires = [
    "setuptools>=40.8.0",
    "wheel",
    "taichi",
    "numpy",
    "noise",
    "scipy",
    "tqdm",
    "opencv-python"
]
